spring:
  config:
    import:
      - optional:file:env/spring.env[.properties]

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 6000ms

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximumPoolSize: 20
      minimumIdle: 5
      idleTimeout: 240000
      maxLifetime: 280000
      keepaliveTime: 150000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

  api:
    service-key: ${API_AIRPORT_PARKING_KEY}
    parking-base-url: http://openapi.airport.co.kr/service/rest/AirportParkingCongestion/airportParkingCongestionRT
    congestion-base-url: https://api.odcloud.kr/api/getAPRTPsgrCongestion_v2/v1/aprtPsgrCongestion%E2%80%8BV2
    apron-base-url: http://openapi.airport.co.kr/service/rest/FlightApronStateList/getFlightApronStatusList
    holiday-base-url: https://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/getRestDeInfo

  logging:
    level:
      org.springframework.web.reactive.function.client: DEBUG

server:
  timezone: Asia/Seoul
